import React from 'react';

export function AINewsSection({ newsSentiment }) {
  if (!newsSentiment || !newsSentiment.summary) return null;

  return (
    <section id="ai-news" className="ai-news-section reveal-up" style={{ padding: '2rem', background: 'linear-gradient(135deg, rgba(37, 99, 235, 0.05), rgba(59, 130, 246, 0.05))', borderRadius: '12px', border: '1px solid rgba(37, 99, 235, 0.2)', marginBottom: '2rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', marginBottom: '1rem', gap: '0.5rem' }}>
        <span style={{ fontSize: '1.5rem' }}>🤖</span>
        <h2 style={{ margin: 0, fontSize: '1.5rem', color: 'var(--primary-color)' }}>AI News & Sentiment Analysis</h2>
      </div>
      
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', marginBottom: '1rem' }}>
          <div style={{ background: 'var(--surface)', padding: '0.75rem 1rem', borderRadius: '8px', border: '1px solid var(--border-color)', flex: 1, minWidth: '150px' }}>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Sentiment Score</div>
            <div style={{ fontSize: '1.25rem', fontWeight: 600, color: 'var(--text-primary)' }}>{newsSentiment.score != null ? Number(newsSentiment.score).toFixed(1) : 'N/A'} / 10</div>
          </div>
          <div style={{ background: 'var(--surface)', padding: '0.75rem 1rem', borderRadius: '8px', border: '1px solid var(--border-color)', flex: 1, minWidth: '150px' }}>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Market Outlook</div>
            <div style={{ fontSize: '1.25rem', fontWeight: 600, color: newsSentiment.label === 'Positive' ? 'var(--success-color)' : newsSentiment.label === 'Negative' ? 'var(--error-color)' : 'var(--text-primary)' }}>
              {newsSentiment.label}
            </div>
          </div>
        </div>

        <div style={{ background: 'var(--surface)', padding: '1.5rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
          <h3 style={{ fontSize: '1.1rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span>📰</span> Latest News Summary
          </h3>
          <p style={{ lineHeight: 1.6, color: 'var(--text-primary)' }}>{newsSentiment.summary}</p>
          <div style={{ marginTop: '1rem', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
            Analyzed from {newsSentiment.articles} recent articles. Last updated: {new Date(newsSentiment.fetched_at).toLocaleDateString()}
          </div>
        </div>
      </div>

      <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontStyle: 'italic', borderTop: '1px solid rgba(0,0,0,0.1)', paddingTop: '1rem' }}>
        <strong>Disclaimer:</strong> This analysis is AI-generated by aggregating recent public news and data. It is provided for informational and context purposes only and may contain inaccuracies. It does not constitute financial, investment, or property advice. Always conduct your own independent research and consult a professional before making financial decisions.
      </div>
    </section>
  );
}
